### ISSUE TITLE
Battery drains really fast while using for some reason,

### ISSUE THREAD

**Issue by CallMeEchoCodes** [RoootTheFox/catppuccin-ios#1]
This appears to be an iOS 16 thing as @RoootTheFox doesn't have this issue.

I'm 99% sure it's caused by the `UIColorFromRGB` macro having a bunch of expensive math operations.

**Comment by RoootTheFox** [comment]
is that still happening with the new tweak version btw? if not I'd like to close this

**Comment by RoootTheFox** [comment]
since this uses your ColorHelper for theming, i think this should no longer be an issue so I'll close this for now - if the issue persists, please reopen !!
